name: Deploy AAR to GitHub packages

on:
  release:
    types:
      - released

jobs:
  deploy_release_aar:
    runs-on: ubuntu-latest
    env:
      GPR_USER: ${{ secrets.GPR_USER }}
      GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          clean: false
      - name: Generate AAR
        run: ./gradlew renderscript-toolkit:assemble --stacktrace
      - name: Publish AAR to GitHub packages
        run: ./gradlew renderscript-toolkit:publish --stacktrace